name: Gitleaks Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Automatically installs the latest stable version of the Gitleaks binary safely
      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          run-scan: false # Prevents it from running the default action scan so you can use your custom CLI commands below

      - name: Run Gitleaks
        run: |
          gitleaks detect \
            --source="." \
            --config=".gitleaks.toml" \
            --report-format=sarif \
            --report-path=results.sarif \
            --verbose
